{% set name = "PasteDeploy" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9ddbaf152f8095438a9fe81f82c78a6714b92ae8e066bed418b6a7ff6a095a95

build:
  number: 0
  skip: true # [py<37] 
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools >=41
  run:
    - python
    - importlib-metadata  # [py<38]

test:
  imports:
    - paste
    - paste.deploy
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://docs.pylonsproject.org/projects/pastedeploy
  license: MIT
  license_family: MIT
  license_file: license.txt
  summary: Load, configure, and compose WSGI applications and servers
  description: |
    This tool provides code to load WSGI applications and servers from URIs.
    These URIs can refer to Python eggs for INI-style configuration files.
    Paste Script provides commands to serve applications based on this configuration file.
  doc_url: https://docs.pylonsproject.org/projects/pastedeploy/
  dev_url: https://github.com/Pylons/pastedeploy

extras:
  recipe-maintainers:
    - mingwandroid
    - mgralczyk
